# Generated by Django 2.1.4 on 2018-12-19 07:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('price', models.IntegerField(verbose_name='Стоимость')),
                ('delivery_period', models.CharField(max_length=50, verbose_name='Ориентировочное время доставки')),
            ],
            options={
                'verbose_name': 'Доставка',
                'verbose_name_plural': 'Доставки',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_product', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name='Кол-во товара')),
                ('status', models.CharField(choices=[('Пол.', 'Получено'), ('Обр.', 'Обработано'), ('Отп.', 'Отправлено')], default='Пол.', max_length=20, verbose_name='Статус')),
                ('name_client', models.CharField(max_length=150, verbose_name='Имя клиента')),
                ('phone_client', models.CharField(max_length=150, verbose_name='Телефон клиента')),
                ('adress_client', models.CharField(max_length=250, verbose_name='Адрес клиента')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.Delivery', verbose_name='Доставка')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='Описание')),
                ('price', models.IntegerField(verbose_name='Стоимость')),
                ('photo', models.ImageField(upload_to='', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.Product', verbose_name='Товар'),
        ),
    ]
